title: ROS 命令速查
title_en: ROS Command Reference
author: 老张同志
email: example@163.com
description: 开源的 ROS 1 / ROS 2 命令查找工具
description_en: An open-source ROS 1 / ROS 2 command reference tool
lang: zh-CN
baseurl: "/ros_ws"
url: "https://1q08.github.io"

# 社交链接
github_username: 1Q08
rss: rss

# 文章摘要显示
show_excerpts: true

# Minima 日期格式
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# 主题
theme: minima

# minima 2.5 导航配置
header_pages:
  - about.md
  - commands.html
  - archive.md

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
